### ISSUE TITLE
Only use one JS module system

### ISSUE THREAD

**Issue by nrc** [nrc/rustw#132]
There's a weird mix of node.js and es6 module imports, we should have just one kind (I think).

**Comment by AlexPikalov** [comment]
Hi @nrc,

Can I pick up this issue, or somebody works on that?

**Comment by nrc** [comment]
@AlexPikalov it would be great if you could pick this up, thank you! Do you know what to do, or would you like a couple of pointers?

**Comment by AlexPikalov** [comment]
I guess I know what to do. Then I'll start working on that.
Thanks.
