### ISSUE TITLE
compiling inside the browser

### ISSUE THREAD

**Issue by torpak** [nrc/rustw#137]
Since rust code can be compiled to javascript/webassembly, wouldn't it be possible to build this into a single static page that one could open in a browser without any server or configuration?
Rustc would then run within the browser instead of on the webserver.
I am aware that this would be much work (if at all possible) and outside the scope of this project, but it could greatly reduce the load on the rust playground servers for example, couldn't it?

**Comment by Goyapa** [comment]
The last thing I noticed about  Rust and wasm!
Ingvar Stepanyan - Interaction with real-world JavaScript from compiled Rust https://youtu.be/zxIbTfsOJZE?t=44m53s
There are two closed unsolved issues until now.
https://github.com/rust-lang/rust/issues/41483
