### ISSUE TITLE
rustw on macOS gives "dyld: Library not loaded: @rpath/librustdoc-...dylib"

### ISSUE THREAD

**Issue by jyc** [nrc/rustw#138]
Hi! I tried installing rustw on my Mac and I got the following error:

```
dyld: Library not loaded: @rpath/librustdoc-27406e878ea4fc6f.dylib
  Referenced from: /Users/jyc/.cargo/bin/rustw
  Reason: image not found
```

Is this a known error? Maybe I'm doing something wrong.

**Comment by nrc** [comment]
You could try setting `export LD_LIBRARY_PATH=$(rustc --print sysroot)/lib:$LD_LIBRARY_PATH`. There is some more discussion of this issue at https://github.com/rust-lang-nursery/rustfmt/issues/1707 (it's a general issue when using nightly Rust programs which reference compiler crates).

Note to self - need to add this to the README

**Comment by jyc** [comment]
Awesome!

Thanks--now `rustw` runs without error. But after navigating to the page in question, I get:

```
io::Error reading or writing path
```

This seems like it probably isn't related--do you know what might be going on? Thanks for the help!

**Comment by nrc** [comment]
> But after navigating to the page in question, I get:

Sorry, I don't understand, which is the "page in question"?

**Comment by jyc** [comment]
Oops, sorry. I mean after navigating to the address output by `rustw`, which for me seems to be http://127.0.0.1:7878/ .

**Comment by nrc** [comment]
Are you running rustw in the directory of a Rust project (i.e., next to a Cargo.toml)? Is there any more output on the console?

**Comment by jyc** [comment]
Hi! I'm running `rustw` in `servo/`, which is next to a Cargo.toml but which maybe uses some special stuff. There is no output on the console.

**Comment by nrc** [comment]
So, Servo is a somewhat complex project to index. It is probably best to try with a simple project to start with to make sure that rustw is working on your system. For Servo, you need to run in `ports/servo`. You'll need a rustw.toml file in there with `source_directory = "."`. That should work, but I haven't tested recently so I'll be interested to hear if that works

**Comment by jyc** [comment]
Thanks again! Good call, seems like it does not work in a small test project either--I'm on a Mac, so I'll try later today on my Linux laptop and report back then. Thanks for the help!
