### ISSUE TITLE
Missing dll files

### ISSUE THREAD

**Issue by Aaronepower** [nrc/rustw#72]
When compiling this project I get the following errors when trying to run the program. There is no errors, or warnings during the build.
#### From Command Line

```
error: Process didn't exit successfully: 'target\debug\rustw.exe' (exit code: 3221225781)
```
#### From Explorer

> The program can't start because syntax-sb705824.dll is missing from your computer. Try reinstalling the program to fix this program.
> 
> The program can't start because std-sb705824.dll is missing from your computer. Try reinstalling the program to fix this program.
> 
> The program can't start because rustdoc-sb705824.dll is missing from your computer. Try reinstalling the program to fix this program.
### OS

```
OS: Windows 10 Pro
Version: 1511
OS Build: 10586.218
```
### Rust

```
rustup: 0.1.6
rustc 1.10.0-nightly (b5ba5923f 2016-04-21)
binary: rustc
commit-hash: b5ba5923f8a15f7f06c660442ad895aff15599c0
commit-date: 2016-04-21
host: i686-pc-windows-gnu
release: 1.10.0-nightly
cargo 0.11.0-nightly (867627c 2016-04-21)
```

**Comment by nrc** [comment]
I'm afraid I've never built rustw on Windows (or in fact any Rust binary) so I have no idea what is going on here, sorry. Your best bet is probably asking on `#rust` on irc. The missing dlls are ones which should come with the Rust distro, so I don't know why you can't link them. Please report back here is you manage to solve the issue.

**Comment by retep998** [comment]
Oh, this might actually be an issue for people using multirust. Normally you'd have rust's bin folder in your path, which would include rustc and all its DLLs. However, when using multirust you only have multirust in your path and the rustc shim, but not the DLLs! Thus when linking to the DLL versions of libraries, you end up depending on things that aren't in your path, and it kinda fails.

**Comment by chriskrycho** [comment]
Seeing similar on OS X (10.11.4). Will report back when I get a solution.

**Comment by chriskrycho** [comment]
If you're running with the new [rustup] tool, you can solve this by running e.g. `rustup run nightly <path/to/>rustw`. Until rustw is released on Cargo, etc., I'm probably going to handle this by putting a tiny shell script (or Rust tool, just for giggles!) on my path that does that when I type `rustw`.

[rustup]: https://www.rustup.rs
