### ISSUE TITLE
Problem running: librustdoc.so missing

### ISSUE THREAD

**Issue by azerupi** [nrc/rustw#85]
I am trying to get rustw running, but I am running into a problem:

```
target/debug/rustw: error while loading shared libraries: librustdoc-8102e29f.so: cannot open shared object file: No such file or directory
```

I am using rustup, maybe that could cause some trouble?

**Comment by GyrosOfWar** [comment]
I have the same issue. Interestingly, with `cargo run`, I don't have that problem. I'm using rustup.rs with the following nightly:
```
rustc 1.11.0-nightly (ad7fe6521 2016-06-23)
binary: rustc
commit-hash: ad7fe6521b8a59d84102113ad660edb21de2cba6
commit-date: 2016-06-23
host: x86_64-unknown-linux-gnu
release: 1.11.0-nightly
```

**Comment by nrc** [comment]
Hmm, I've not seen this. It could be due to rustup, and the fact that it resolves when using `cargo run` somewhat suggests that (Cargo might be doing some more work to set paths or something). @azerupi are you using nightly Rust?

**Comment by azerupi** [comment]
Yes, I can't build rustw with stable.

I have rustup installed with stable as default toolchain and an override to nightly in the directory of rustw. Building the project works flawlessly, the error occurs only when running rustw.

I tried setting nightly as default toolchain, but that didn't change anything. Running it with `cargo run` works.
